### ISSUE TITLE
Titlebar on Wayland is not styled properly.

### ISSUE THREAD

**Issue by Pshemas** [flathub/org.blender.Blender#130]
With the current version 3.4.1 the titlebar looks completely out of place (on my end "windows - like" buttons under Gnome). I assume it is because this has enabled Wayland by default... and needs another dependency - libdecor.

**Comment by dani763f** [comment]
+1 same issue on fedora 37 with wayland

**Comment by kevinsmia1939** [comment]
lidecor is included already

**Comment by Pixelnarium** [comment]
Libdecor has no stable release with GTK support. Without libdecor you would not get a titlebar at all on GNOME since GNOME does not support server side decorations.

You can disable Wayland support and force X11 with `flatpak override --nosocket=wayland --socket=x11 org.blender.Blender` or via [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)

**Comment by MiMillieuh** [comment]
Same issue, I confirm that changing it back to X11 fix the issue.

But it should be the default then cause on Nvidia Optimus cards blender won't start unless you use the integrated GPU with wayland.

**Comment by Beryesa** [comment]
> But it should be the default then cause on Nvidia Optimus cards blender won't start unless you use the integrated GPU on wayland, on x11 the issue is gone

Fixed in nvidia 530

**Comment by MiMillieuh** [comment]
The issue has been closed but I still encounter the problem...

**Comment by peterdk** [comment]
Works for me now! Looking great on Ubuntu with 4k 200% scaling. No longer a eye sore.

**Comment by rowbawts** [comment]
Not sure if its the same issue, but I have a proper title-bar that's just not styled properly (dark mode) see Discord for reference.

![Screenshot from 2024-04-07 20-47-38](https://github.com/flathub/org.blender.Blender/assets/13012832/7e2765d9-ff67-42ad-a93f-0af24baafef0)
